debug: true

spring:
  application:
    name: siggi-hook-server

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/test
    type: com.zaxxer.hikari.HikariDataSource

management:
    port: ${MANAGEMENT_PORT:7979}
    security:
        enabled: false

server:
  use-forward-headers: true

security:
  user:
    name: hookie
    password: K17l432Zk9
