logging:
  config: classpath:/config/logback-290.xml

management:
  security:
    enabled: false

spring:
  application:
    name: siggi-hook-server

info:
    application:
        name: siggi-hook-server-${app.instance.id}